version: '3'

services:
  rmq0:
    build: rmq
    hostname: rmq0
    environment:
      - LOG=debug
    volumes:
      - ./data/rmq0:/var/lib/rabbitmq/mnesia
      - ./log/rmq0:/var/log/rabbitmq
    ports:
      # HOST:CONTAINER
      - 15672:15672
  rmq1:
    build: rmq
    hostname: rmq1
    environment:
      - LOG=debug
    volumes:
      - ./data/rmq1:/var/lib/rabbitmq/mnesia
      - ./log/rmq1:/var/log/rabbitmq
    ports:
      # HOST:CONTAINER
      - 15673:15672
  perf-test-0:
    image: pivotalrabbitmq/perf-test:latest
    command:
      - --uri=amqp://rmq0
      - --servers-startup-timeout=10
      - --rate=1
      - --producers=6
      - --consumers=6
      - --flag=persistent
      - --flag=mandatory
      - --confirm=4
    depends_on:
      - rmq0
    restart: on-failure
